// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CachePaths } from "./CachePaths";
import type { ChromecastConfig } from "./ChromecastConfig";
import type { LibrarySource } from "./LibrarySource";

export type AppConfig = {
  data_path: string | null;
  cache_paths: CachePaths | null;
  /**
   * Deprecated. Kept for one-shot migration into `library_source`; never
   * written by code that has been through `with_defaults`.
   */
  last_folder: string | null;
  library_source: LibrarySource | null;
  last_theme: number | null;
  guide_volume: number | null;
  fullscreen: boolean | null;
  dark_mode: boolean | null;
  mic_active: boolean | null;
  /**
   * `serde(alias = "mic_mirroring")` keeps configs written by builds that
   * called this feature "mic mirroring" loading without a manual migration;
   * the next `save` rewrites them under the new name.
   */
  mic_monitoring: boolean | null;
  mic_monitor_gain: number | null;
  mic_latency_compensation_sec: number | null;
  preferred_mic: string | null;
  whisper_model: string | null;
  beam_size: number | null;
  batch_size: number | null;
  last_video_flavor: number | null;
  /**
   * Whether the Pixabay background cycles to a different clip each time
   * the active one finishes playing. `None`/`false` (the default) loops
   * a single clip for the whole song instead -- was unconditional
   * rotation before this setting existed; changed to default off since
   * constantly cutting to a new clip was distracting during playback.
   */
  pixabay_video_rotation: boolean | null;
  lyrics_vertical_position: string | null;
  lyrics_horizontal_position: string | null;
  separator: string | null;
  asr_engine: string | null;
  align_backend: string | null;
  /**
   * Alternative alignment backend, used only for a one-off "Realign
   * (alternative backend)" song action rather than the default
   * `align_backend` used for every other analysis/realign.
   */
  alt_align_backend: string | null;
  vocal_detection_threshold_pct: number | null;
  /**
   * Whether analysis prefers a song's local lyrics source (a `.lrc`
   * sidecar, else an embedded tag -- see `Song::has_external_lyrics`)
   * over ASR transcription when one is available: forced-align that text
   * to the separated vocals instead of transcribing. Off by default --
   * this silently changes what analysis output a song gets, so it's
   * opt-in rather than a surprise for existing installs. When off,
   * analysis behaves exactly as before this setting existed (LRCLIB
   * lookup, then ASR).
   */
  use_external_lyrics: boolean | null;
  auto_analyze: boolean | null;
  /**
   * Whether startup restores the on-disk analysis queue instead of
   * wiping it. When on, every song that was `queued`/`analyzing`/`failed`
   * before shutdown is cleanly re-enqueued (see `enqueue_one`) so work
   * resumes; unlike `auto_analyze` it does not sweep the whole library
   * for anything else unanalyzed. Off by default to preserve existing
   * behavior (clear-on-startup).
   */
  restore_analyze: boolean | null;
  track_analysis_timings: boolean | null;
  /**
   * Whether a library scan/rescan re-checks `has_lrc_file`/
   * `has_embedded_lyrics` for every already-known local song, not just
   * brand-new ones (see `source::folder::refresh_lyrics_flags`). Off by
   * default: it's a real per-song I/O cost (a stat + a tag read) added to
   * every rescan, scaling with library size, so it's opt-in rather than
   * silently changing rescan behavior/performance for every install.
   */
  refresh_lyrics_on_scan: boolean | null;
  song_list_view: string | null;
  language_overrides: { [key in string]: string } | null;
  /**
   * Whether this instance offloads the tail of its analysis queue to
   * another Nightingale instance (see `parallel_analysis_url`) instead of
   * only processing it locally. Off by default -- no peer is configured
   * out of the box.
   */
  parallel_analysis_enabled: boolean | null;
  /**
   * Base URL (e.g. `http://otherhost:8080`) of the peer Nightingale
   * instance to offload analysis to. Only consulted when
   * `parallel_analysis_enabled` is true.
   */
  parallel_analysis_url: string | null;
  /**
   * When on, this instance never processes songs itself -- the local
   * worker (`analyzer::ensure_worker_running`) never starts, and a peer
   * rejecting/timing out on a song leaves it queued for the peer to retry
   * rather than falling back to local processing. Only meaningful
   * alongside `parallel_analysis_enabled`; off by default so a fresh
   * install still analyzes locally with no peer configured.
   */
  parallel_analysis_only: boolean | null;
  /**
   * Chromecast device the `/api/cast` endpoint casts matched songs to.
   * `None` means casting is disabled.
   */
  chromecast: ChromecastConfig | null;
};
