// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CastReceiverMessage = {
  type: "load";
  file_hash: string;
  /**
   * 0.0-1.0 guide-vocal mix level; omitted -> receiver falls back to
   * its own fetched `AppConfig.guide_volume`.
   */
  guide_volume: number | null;
};
