// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Chromecast device to cast matched songs to (see `crate::chromecast`).
 * Persisted in `config.json`; the app has no discovery UI for this yet, so
 * the host/port are hand-entered by the operator.
 */
export type ChromecastConfig = {
  host: string;
  port: number;
  /**
   * Overrides LAN-IP auto-detection for the base URL the Chromecast uses
   * to fetch media from this server (e.g. "http://192.168.1.50:8080").
   * Needed when auto-detection picks the wrong network interface on a
   * multi-homed host.
   */
  server_base_url: string | null;
  /**
   * When true, cast a pre-rendered video with burned-in background +
   * title/artist + word-timed lyrics (`crate::karaoke_video`) instead of
   * the song's raw audio. Requires the song to already have a
   * transcript. Off by default -- preserves the original audio-only
   * casting behavior for anyone who doesn't opt in. Ignored when
   * `receiver_app_id` is set (the custom receiver always renders the
   * background + lyrics live, there's nothing to pre-render).
   */
  karaoke_video: boolean;
  /**
   * Custom Cast Receiver app ID from the Cast Developer Console. When
   * set, `cast_song_to_configured_device` launches this receiver instead
   * of DefaultMediaReceiver and drives it via a `urn:x-cast:...` message
   * (`crate::cast_protocol`) instead of `media.load` -- the receiver
   * fetches everything else (transcript, stems, background) itself,
   * same-origin against this server. `None` (default) preserves the
   * existing DefaultMediaReceiver + media.load behavior unchanged.
   */
  receiver_app_id: string | null;
};
