// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Coarse cause for a `QueuedStatus::Failed`, set at the point in
 * `process_song`/`finalize_song` where the failure is known -- lets callers
 * (the UI) group failures without pattern-matching the free-form message.
 */
export type FailureKind =
  | "AudioPrep"
  | "ServerStartup"
  | "ServerCrash"
  | "GpuOom"
  | "Worker"
  | "MissingOutput"
  | "Other";
