// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LyricsFile = {
  lines: Array<string>;
  /**
   * Best-effort per-line timing anchors sourced from LRCLIB's
   * `syncedLyrics`, fuzzy-matched against `lines` in the same order (see
   * `match_synced_anchors`). Same length as `lines` when present; `None`
   * entries mark lines with no confident match. Absent entirely when no
   * LRCLIB synced source was found/available.
   *
   * Consumed only by the Python analyzer (`align.py`) as alignment-window
   * hints to shrink each forced-alignment segment from "the whole song"
   * to "around this one line" -- never as the displayed lyric text or
   * wording, which remains `lines`, sourced independently and possibly
   * from a different provider than these anchors.
   */
  line_anchors?: Array<number | null> | null;
};
