// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Marks that playback actually started for a song, independent of whether it
 * was ever scored. Lets a later analysis compare this against `scores` to
 * compute songs played without being scored.
 */
export type PlayRecord = { profile: string, song_hash: string, played_at: bigint, };
