// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FailureKind } from "./FailureKind";

export type QueuedStatus =
  | "Queued"
  | { Analyzing: number }
  | {
      Failed: {
        kind: FailureKind;
        message: string;
        /**
         * Set by `acknowledge_failures`; false whenever this row was
         * (re)written by a failure, i.e. every failure starts as "new".
         */
        acknowledged: boolean;
      };
    };
