// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FailureKind } from "./FailureKind";

export type QueuedStatus =
  | "Queued"
  | { Analyzing: number }
  | { Failed: { kind: FailureKind; message: string } };
