// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SongOrigin } from "./SongOrigin";
import type { TranscriptSource } from "./TranscriptSource";
import type { UsdxBundle } from "./UsdxBundle";

export type Song = {
  path: string;
  file_hash: string;
  title: string;
  artist: string;
  album: string;
  genre: string;
  duration_secs: number;
  album_art_path: string | null;
  is_analyzed: boolean;
  language: string | null;
  transcript_source: TranscriptSource | null;
  key: string | null;
  override_key: string | null;
  tempo: number;
  key_offset: number;
  is_video: boolean;
  usdx: UsdxBundle | null;
  origin: SongOrigin;
  /**
   * True when the song was made playable from provided LRC without stem
   * separation: playback uses the original mix and the guide control is
   * hidden. Defaults to `false` for stem-separated songs.
   */
  no_stems: boolean;
  /**
   * True when a `.lrc` sidecar sits next to the audio file (same
   * directory, same basename, `.lrc` extension). Always `false` for
   * remote-source songs (Jellyfin/Navidrome/Plex) -- their bytes aren't
   * local at scan time.
   */
  has_lrc_file: boolean;
  /**
   * True when the audio file's own tags carry non-empty lyrics (ID3
   * `USLT` / MP4 `©lyr`, via lofty's `ItemKey::Lyrics`). Always `false`
   * for video files (no tag read attempted) and remote-source songs.
   */
  has_embedded_lyrics: boolean;
};
