// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Song } from "./Song";

export type SongsStore = {
  count: number;
  folder: string;
  processed: Array<Song>;
  processed_count: number;
  /**
   * Count of songs matching the current filter that are already analyzed.
   * Lets the frontend gate analyzed-only bulk actions
   */
  analyzed_count: number;
};
