// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SongOrigin } from "./SongOrigin";
import type { TranscriptSource } from "./TranscriptSource";
import type { UsdxBundle } from "./UsdxBundle";

export type Song = {
  path: string;
  file_hash: string;
  title: string;
  artist: string;
  album: string;
  genre: string;
  duration_secs: number;
  album_art_path: string | null;
  is_analyzed: boolean;
  language: string | null;
  transcript_source: TranscriptSource | null;
  /**
   * Which forced-alignment backend actually produced this song's current
   * timing (`"whisperx"`, `"ctc"`, or `"qwen"`). `None` for `Lrc`/`Usdx`
   * sources and for songs analyzed before this field existed, until they're
   * realigned or backfilled.
   */
  align_backend: string | null;
  key: string | null;
  override_key: string | null;
  tempo: number;
  key_offset: number;
  is_video: boolean;
  usdx: UsdxBundle | null;
  origin: SongOrigin;
  /**
   * True when the song was made playable from provided LRC without stem
   * separation: playback uses the original mix and the guide control is
   * hidden. Defaults to `false` for stem-separated songs.
   */
  no_stems: boolean;
  /**
   * True when a `.lrc` sidecar sits next to the audio file (same
   * directory, same basename, `.lrc` extension). Always `false` for
   * remote-source songs (Jellyfin/Navidrome/Plex) -- their bytes aren't
   * local at scan time.
   */
  has_lrc_file: boolean;
  /**
   * True when the audio file's own tags carry non-empty lyrics (ID3
   * `USLT` / MP4 `©lyr`, via lofty's `ItemKey::Lyrics`). Always `false`
   * for video files (no tag read attempted) and remote-source songs.
   */
  has_embedded_lyrics: boolean;
  /**
   * True when a reel-background karaoke video has been rendered and
   * cached for this song. Unlike `has_lrc_file`/`has_embedded_lyrics`,
   * not computed at scan time -- sourced from the `karaoke_video_status`
   * side table and mirrored onto this field whenever
   * `karaoke_video::ensure_karaoke_video` succeeds, so the song list can
   * show it per row without an extra query. See
   * `library_db::get_karaoke_video_status`.
   */
  has_karaoke_video: boolean;
  /**
   * Same as `has_karaoke_video`, for the YouTube-background render --
   * see `karaoke_video::ensure_youtube_background_karaoke_video`.
   */
  has_youtube_karaoke_video: boolean;
};
