// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SyncResult = {
  /**
   * Seconds into the video where the song's own timeline (its own t=0)
   * actually begins. Positive means the video has extra content before
   * the song starts (e.g. an intro) that should be trimmed off before
   * compositing it as a karaoke background.
   */
  video_offset_secs: number;
  /**
   * Correlation strength at `video_offset_secs`, roughly 0..1 in
   * practice. Always `>= CONFIDENCE_THRESHOLD` when `Some` is returned.
   */
  confidence: number;
};
