// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VideoQueueKind } from "./VideoQueueKind";
import type { VideoQueueStage } from "./VideoQueueStage";

export type VideoQueueEntry = { file_hash: string; kind: VideoQueueKind; stage: VideoQueueStage };
