// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VideoQueueEntry } from "./VideoQueueEntry";

export type VideoProcessingQueue = { entries: Array<VideoQueueEntry> };
