// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A downloaded YouTube video that's confidently synced to `file_hash`'s own
 * audio -- ready to play live as a background (`Background`'s `"youtube"`
 * theme, both desktop and the Chromecast receiver), muted, with the song's
 * own audio/vocals mixed separately and the video's playback position
 * offset by `offset_secs` to keep the two timelines aligned.
 */
export type YoutubeBackground = {
  /**
   * Absolute server-local path, resolved into a playable URL the same
   * way `Song.path`/`sourceVideoPath` are (`/api/asset` or the Tauri
   * media server) -- not a public URL by itself.
   */
  video_asset_path: string;
  offset_secs: number;
};
